version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /usr/src/app/frontend
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173" # Assuming frontend runs on 3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    working_dir: /usr/src/app/backend
    command: ["node", "server"]
    ports:
      - "5003:5003"
    depends_on:
      - frontend
